### PR TITLE
correct slot for calibration `method`

### LINKED ISSUE #44: The fit functions are looking for the calibration method in the wrong place
I think that this line: 

https://github.com/tidymodels/tailor/blob/3385fbce71a7eb82bad53c8ced6c3463dc7c9a87/R/adjust-numeric-calibration.R#L87

should be `check_method(object$argument$method, tailor$type)` since that slot is where the value is saved. 

I think that the same is true for `fit.probability_calibration()`. 

I think that all of the calibration types are accidentally defaulting to linear/logistic because of this.

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #44.

### CODE REVIEW

File: tests/testthat/test-adjust-probability-calibration.R [hunk 1]
```diff
@@ -43,6 +43,50 @@ test_that("basic adjust_probability_calibration() usage works", {
...
+  d_test <- two_class_example[!in_rows, ]
+
+  # fitting and predicting happens without raising conditions
+  expect_no_condition(
+    tlr <-
+      tailor() %>%
+      adjust_probability_calibration(method = "isotonic")
+  )
+
+  skip("TODO: cannot run until #49 is merged")
```
Comment (simonpcouch) [inline tests/testthat/test-adjust-probability-calibration.R:63]: Related to #49--will need a merge upstream then.
